apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: demo
  labels: 
    app: demo
    run: demo
spec:
  containers:
    - image: us-west1-docker.pkg.dev/devops-419716/kbot/demo:v1.0.0
      name: app
      ports:
        - containerPort: 8000
          name: http
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
