apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
  namespace: demo
  labels: 
    app: demo
    run: demo
spec:
  containers:
    - name: my-app-container
      image: your-container-image:tag
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
